xmlDir data/xml
en_art data/yuliao/EN
cn_art data/yuliao/CN
en_dict data/en_dict.txt
cn_dict data/cn_dict.txt
en_index data/en_index.txt
cn_index data/cn_index.txt

ripepageLib data/ripepage.lib
newRipepageLib data/newRipepage.lib
newOffsetLib data/newOffset.lib
invertIndex data/invertIndex.lib
offsetLib data/offset.lib

dict data/dict/jieba.dict.utf8
hmm_model data/dict/hmm_model.utf8
idf data/dict/idf.utf8
stop_words data/dict/stop_words.utf8
user_dict data/dict/user.dict.utf8


